### ISSUE TITLE
Deferred blocks are breaking the renderBlock API of Twig

### ISSUE THREAD

**Issue by stof** [rybakit/twig-extensions-deferred#22] opened 2024-04-17 12:25 UTC
By hijacking the core concept of blocks and changing entirely the behavior of rendering a block, this extension breaks the usage of blocks through the `renderBlock` API of Twig.

**Comment by rybakit** [comment] 2024-04-17 21:06
@stof 
> changing entirely the behavior of rendering a block

That's the main point of this extension, as Twig's "core concept" is limited and doesn't allow the implementation of this very trivial feature without "hijacking" the compiler. I haven't checked the Twig internals for a while; has anything changed in that regard? If not, I don't really understand the purpose of this issue and what outcome you would expect from it.

**Comment by stof** [comment] 2024-04-17 22:29
Twig has a public API to render blocks instead of templates. The way this extension works breaks this public API of Twig (and then, we get issues in the Twig issue tracker about Twig being broken, which might not even mention that this extension is used).
Note that I'm not talking about Twig internals here (where things indeed changed, but that's more about #20). I'm talking about the public API.

**Comment by rybakit** [comment] 2024-04-26 18:39
> Twig has a public API to render blocks instead of templates.

This is great. I'd be happy to learn from you how to do what this extension does using only the public API. Feel free to create a pull request.

**Comment by rybakit** [comment] 2024-05-01 09:23
Closing as duplicate of https://github.com/rybakit/twig-deferred-extension/issues/20.

**Closed as completed by rybakit** 2024-05-01 09:23 UTC
